language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

before_install:
  - [[ "$TRAVIS_OS_NAME" == 'linux' ]] && sudo apt-get update
  - [[ "$TRAVIS_OS_NAME" == 'linux' ]] && sudo apt-get install -y capnproto
  - [[ "$TRAVIS_OS_NAME" == 'mac' ]]   && brew update
  - [[ "$TRAVIS_OS_NAME" == 'mac' ]]   && brew install capnp

script:
  cargo build --verbose

matrix:
  allow_failures:
    - rust: nightly
cache: cargo

# vim: set sw=2 ts=2:
