[package]
name = "striking-db"
version = "0.0.1"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]

[dependencies]
cfg-if = "0.1"
lazy_static = "0.2"
lru_time_cache = "0.7"
num_cpus = "1.6"
parking_lot = "0.4"
stable_deref_trait = "1.0"

[target.'cfg(unix)'.dependencies]
nix = "0.9"
